name: Build
on:
  push:
    branches: [main]
  workflow_dispatch: # Enable manual build command

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build
